// lib/messenger.ts
//
// Sending a DM from somewhere other than the webhook.
//
// ─────────────────────────────────────────────────────────────
// THE 24-HOUR WINDOW, AND WHY THIS FUNCTION REPORTS FAILURE
// INSTEAD OF SWALLOWING IT
//
// Instagram only lets a business send a message within 24 hours of
// the customer's own last message. Outside that window Meta rejects
// the send. It does not queue it, it does not deliver it late, and
// the customer never learns anything went wrong.
//
// There IS an official way around it — the Human Agent tag, which
// extends the window to 7 days — but it requires passing Meta's App
// Review with Business Verification, which is the whole thing this
// project is set up to avoid. So: 24 hours is what we have.
//
// That makes the failure case ordinary, not exceptional. A shop that
// ships two days after the payment slip will hit it routinely. So
// this returns a result the caller can act on rather than logging an
// error nobody reads — the dashboard uses it to hand the owner the
// message text to paste themselves.
// ─────────────────────────────────────────────────────────────

import { eq, and } from 'drizzle-orm';
import { db, getShopId } from './db';
import { conversations } from './db/schema';
import { markBotSent } from './memory';

const GRAPH = 'https://graph.instagram.com/v23.0/me/messages';

export type SendResult =
  | { ok: true }
  | { ok: false; windowClosed: boolean; error: string };

/**
 * Send one text message to a customer.
 *
 * Same endpoint and token the webhook uses. It lives here rather
 * than staying private inside the webhook route so the dashboard can
 * reach it without importing a route handler — which would drag the
 * whole webhook, and everything it imports, along with it.
 */
export async function sendDM(recipientId: string, text: string): Promise<SendResult> {
  if (!process.env.IG_ACCESS_TOKEN) {
    return { ok: false, windowClosed: false, error: 'IG_ACCESS_TOKEN is not set' };
  }

  // Record before sending. The webhook receives an echo of every
  // message the account sends, and this is what stops it treating
  // our own message as something the seller typed by hand.
  await markBotSent(text);

  try {
    const res = await fetch(GRAPH, {
      method: 'POST',
      headers: {
        authorization: `Bearer ${process.env.IG_ACCESS_TOKEN}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        recipient: { id: recipientId },
        message: { text },
      }),
    });

    const data = await res.json().catch(() => ({} as any));
    if (res.ok) return { ok: true };

    // Meta reports the closed window as code 10 with subcode
    // 2534022. Treating it as its own outcome is what lets the
    // dashboard say "outside the 24-hour window, here is the text to
    // paste" rather than the useless "sending failed".
    const code = data?.error?.code;
    const subcode = data?.error?.error_subcode;
    const windowClosed = subcode === 2534022 || code === 10;

    return {
      ok: false,
      windowClosed,
      error: data?.error?.message ?? `HTTP ${res.status}`,
    };
  } catch (err: any) {
    return { ok: false, windowClosed: false, error: err?.message ?? 'network error' };
  }
}

/**
 * Which language this customer's thread is in.
 *
 * Read from the conversations table, not from Redis: the Redis copy
 * expires after a day, and an order being shipped is very often
 * older than that. Defaults to Thai, which is also what the bot
 * defaults to.
 */
export async function threadLang(customerId: string): Promise<'th' | 'en'> {
  try {
    const shopId = await getShopId();
    const [row] = await db
      .select({ lang: conversations.lang })
      .from(conversations)
      .where(
        and(eq(conversations.shopId, shopId), eq(conversations.customerId, customerId))
      )
      .limit(1);
    return row?.lang === 'en' ? 'en' : 'th';
  } catch {
    return 'th';
  }
}

/**
 * The shipped-with-tracking message.
 *
 * Written out here, not generated by the model. It contains an order
 * number and a tracking number, and the rule on this project is that
 * the model never produces a number a customer will act on — a
 * plausible-looking wrong tracking number is worse than none, because
 * the customer spends a day checking a courier site for a parcel that
 * was never sent under that code.
 */
export function shippedMessage(opts: {
  orderNo: string;
  tracking: string;
  carrier: string;
  lang: 'th' | 'en';
}): string {
  const { orderNo, tracking, carrier, lang } = opts;

  if (lang === 'en') {
    return [
      `Your order ${orderNo} has been shipped.`,
      carrier ? `Courier: ${carrier}` : '',
      `Tracking number: ${tracking}`,
      `You can track it on the courier's website. Thank you!`,
    ]
      .filter(Boolean)
      .join('\n');
  }

  return [
    `ออเดอร์ ${orderNo} จัดส่งแล้วค่ะ`,
    carrier ? `ขนส่ง: ${carrier}` : '',
    `เลขพัสดุ: ${tracking}`,
    `เช็กสถานะได้ที่เว็บของขนส่งเลยนะคะ ขอบคุณค่ะ`,
  ]
    .filter(Boolean)
    .join('\n');
}